import React from 'react';
import './Footer.css';

/**
 * Footer — Premium dark glassmorphic footer with editorial layout.
 */
function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="footer">
      {/* AI Legal Disclaimer (Apple-style fine print) */}
      <div className="footer__legal container">
        <p>
          ClauseGuard AI utilizes advanced adversarial multi-agent intelligence to parse, analyze, and critique complex contracts, offer letters, quotations, ticket terms, and online policies. While our adversarial agents are explicitly trained to uncover exploitative clauses, hidden liabilities, legal ambiguities, and real-world risks, AI systems can make mistakes. The analyses, risk scores, red flags, and highlighted gaps generated by our platform are designed solely to aid in your personal understanding—they do not, and should not, constitute professional, legal, or financial advice. We strongly advise against relying exclusively on these automated insights for determining rights, making commercial decisions, or entering into legally binding agreements. Always review the full text of your official documents and consult with a qualified legal professional when you have significant concerns. By utilizing this service, you acknowledge that its purpose is for informational ease, and the developers assume no liability for misinterpretations or financial actions taken based on its output. Know the risk before you agree.
        </p>
      </div>

      <div className="footer__divider container" />

      <div className="footer__inner container">
        {/* Brand Column */}
        <div className="footer__brand">
          <div className="footer__logo">
            <span className="footer__logo-mark">C</span>
            <span className="footer__logo-text">ClauseGuard AI</span>
          </div>
          <p className="footer__tagline">
            Know the risk before you agree. We analyze agreements to detect exploitative 
            clauses and hidden liabilities so you never sign a bad contract.
          </p>
        </div>

        {/* Link Columns */}
        <div className="footer__links">
          <div className="footer__col">
            <h4 className="footer__col-title">Product</h4>
            <a href="/workspace" className="footer__link">Analysis Workspace</a>
            <a href="/dashboard" className="footer__link">Risk Dashboard</a>
            <a href="/compare" className="footer__link">Contract Comparison</a>
          </div>
          <div className="footer__col">
            <h4 className="footer__col-title">Account</h4>
            <a href="/login" className="footer__link">Log In</a>
            <a href="/signup" className="footer__link">Create Account</a>
            <a href="/settings" className="footer__link">Settings & Export</a>
          </div>
          <div className="footer__col">
            <h4 className="footer__col-title">Resources</h4>
            <span className="footer__link footer__link--muted">Documentation</span>
            <span className="footer__link footer__link--muted">Privacy Policy</span>
            <span className="footer__link footer__link--muted">Terms of Service</span>
          </div>
        </div>
      </div>

      <div className="footer__divider container" />

      {/* Bottom Bar */}
      <div className="footer__bottom container">
        <p className="footer__copy">
          Copyright © {currentYear} ClauseGuard AI Inc. All rights reserved.
        </p>
      </div>
    </footer>
  );
}

export default Footer;
